//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//
//     このファイルへの変更は、正しくない動作の原因となる場合があります。
//     また、コードの再生成時には変更が失われます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    public partial class Form1
    {
        protected global::System.Web.UI.WebControls.TextBox txtOrderID;
        protected global::System.Web.UI.WebControls.Button btnLoad;
        protected global::System.Web.UI.WebControls.TextBox txtOrderDate;
        protected global::System.Web.UI.WebControls.TextBox txtRequiredDate;
        protected global::System.Web.UI.WebControls.TextBox txtShippedDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerPhone;
        protected global::System.Web.UI.WebControls.Label lblCustomerAddress;
        protected global::System.Web.UI.WebControls.DropDownList ddlEmployee;
        protected global::System.Web.UI.WebControls.Label lblEmployeeTitle;
        protected global::System.Web.UI.WebControls.Label lblEmployeeExtension;
        protected global::System.Web.UI.WebControls.Label lblTotalAmount;
        protected global::System.Web.UI.WebControls.GridView gvDetails;
        protected global::System.Web.UI.WebControls.Button btnAddDetail;
        protected global::System.Web.UI.WebControls.DropDownList ddlShipper;
        protected global::System.Web.UI.WebControls.Label lblShipperPhone;
        protected global::System.Web.UI.WebControls.TextBox txtFreight;
        protected global::System.Web.UI.WebControls.TextBox txtShipName;
        protected global::System.Web.UI.WebControls.TextBox txtShipAddress;
        protected global::System.Web.UI.WebControls.TextBox txtShipCity;
        protected global::System.Web.UI.WebControls.TextBox txtShipRegion;
        protected global::System.Web.UI.WebControls.TextBox txtShipPostalCode;
        protected global::System.Web.UI.WebControls.TextBox txtShipCountry;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}
